import React from 'react'
import { CardLeft } from '../become_a_tasker/CardLeft'
import { OurStory } from '../Component/share/OurStory';
import { CardRight } from './CardRight';
import { CurrentOpeningcard } from './CurrentOpeningcard';
import { Subcribe } from '../Component/share/Subcribe';
import { MobileOurstory } from '../Component/share/mobileOurstory';
import { MobileCardLeft } from '../Whoweare/MobileCardLeft';
import { MobileSubcribe } from '../Component/share/mobileSubcribe';

export const metadata = {
  title: 'Career',
  description: 'Generated by create next app',
}

const Career = () => {
  return (
    <main>
     <div className='desktopboxdisplay'>
     <OurStory title="Empower Your" subtitle="Career with Us" para="Empower people to supercharge their
productivity by becoming part of the growing
team at Local Tasker" btnvalue="View Opportunities" img1="/circle1career.png" img2="/bigcirclecareer.png" link='/'/>
     </div>
     <div className='mobiledisplay'>
      <MobileOurstory title="Empower Your" subtitle="Career with Us" para="Empower people to supercharge their productivity by
becoming part of the growing team at Local Tasker" btnvalue="Hire a Tasker" img="/assets/careermobile.JPG" link='https://localtasker.thedatech.com/register?type=2'/>
    </div>
    <div className='desktopboxdisplay'>
    <CardLeft title="Are you mission driven!" para1="At Local Tasker, we re more than just a company we re a
community. We connect individuals in need of services
with those who have the skills to help. Our mission is to
simplify everyday tasks for people all over the UK, and we
are always on the lookout for talented and dedicated
individuals to join our team." para2="Joining Local Tasker means becoming a part of a
dynamic community that values collaboration,
innovation, and most importantly, the satisfaction of our
customers. If you have a passion for service, a
commitment to excellence, and a desire to support local
communities, we would love to hear from you." btnvalue="View Opportunities" img="/whyLT.png"/>
    </div>
    <MobileCardLeft title="Are you mission driven!" para1="At Local Tasker, we re more than just a company - we re
a community. We connect individuals in need of
services with those who have the skills to help. Our
mission is to simplify everyday tasks for people all over
the UK, and we are always on the lookout for talented
and dedicated individuals to join our team." para2="Joining Local Tasker means becoming a part of a
dynamic community that values collaboration,
innovation, and most importantly, the satisfaction of our
customers. If you have a passion for service, a
commitment to excellence, and a desire to support local
communities, we would love to hear from you." para3="" img="/whyLT.png"/>
    <CardRight/>
    <CurrentOpeningcard/>
    <div className='desktopboxdisplay'><Subcribe/></div>
    <MobileSubcribe/>
    </main>
  )
}

export default Career